export type Usuario = {
    id_usuario: number;
    id_especialidad: number;
    id_medico: number;
    id_municipio: number;
    nombre: string;
    apellidos: string;
    usuario: string;
    pass: string;
    tipo: number;
    estatus: number;
    acceso_app: number;
    telefono: string;
    correo: string;
    direccion: string;
    sobre_mi: string;
    telefono_urgencias: string;
    whatsapp: string;
    estatus_web: number;
    experiencia: string;
    facebook: string;
    twitter: string;
    instagram: string;
    web: string;
    enlace: string;
};